server:
  listen: ":8080"

code_runner:
  listen: ":9000"

database:
  dsn: "host=db user=myuser password=mysecurepassword dbname=go_judge sslmode=disable TimeZone=UTC"

session:
  secret: "q4MwdoFCRgBUyg2gGjRyx33ZMHj1dX4kAjZgpEPqga3A9eA3QQ"