services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:     myuser
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB:       go_judge
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d go_judge"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  code-runner:
    build:
      context: .
      dockerfile: cmd/code-runner/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9000:9000"

volumes:
  db_data: